version: '3.8'

services:
  postgres-profile:
    image: postgres:13
    container_name: postgres-profile
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    networks:
      - backend

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: profile-service:latest
    container_name: profile-container
    ports:
      - "8083:8083"
    depends_on:
      - postgres-profile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-profile:5432/profile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - backend

networks:
  backend:
